{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rcvr-dmarc.serviceAccountName" . }}
  labels:
{{ include "rcvr-dmarc.labels" . | nindent 4 }}
{{- end -}}
